test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4b1297d8.name = "Upgrade from  2.3.0"
    test_upgrade_from.4b1297d8.args.admin    = "package_checker"
    test_upgrade_from.4b1297d8.args.password = "much_s3cur1ty"
    test_upgrade_from.4b1297d8.args.domain   = "domain.tld"
