#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_go
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=5

	# Download, check integrity, uncompress and patch the source from app.src
	if [ $YNH_ARCH == "armhf" ] || [ $YNH_ARCH == "arm64" ]
	then
		ynh_setup_source --dest_dir="$install_dir/build" --keep="$install_dir/config.toml"
		# Install Nodejs
		ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version
		# Install Yarn

		# Install Go
		ynh_exec_warn_less ynh_install_go --go_version=$GO_VERSION
		pushd "$install_dir/build"
			# Build the sources
			ynh_use_go
			export GOPATH="$install_dir/build/go"
			export GOCACHE="$install_dir/build/.cache"
			ynh_use_nodejs
			make dist
			mv listmonk ..
		popd
		ynh_remove_go
		ynh_remove_nodejs
		ynh_secure_remove --file="$install_dir/build"
	else
		ynh_setup_source --dest_dir="$install_dir"  --source_id=$YNH_ARCH --keep="$install_dir/config.toml"
	fi
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod +x "$install_dir/listmonk"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# DATABASE CONFIGURATION
#=================================================
ynh_script_progression --message="Generating database..." --weight=1

pushd "$install_dir"
	yes | ./listmonk --upgrade
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=2

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add $app --description="Newsletter and mailing list manager" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

ynh_systemd_action --service_name=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
